version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: financas_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: financas
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: financas_api
    environment:
      DATABASE_URL: mysql+pymysql://app_user:app_password@db:3306/financas?charset=utf8mb4
      JWT_SECRET_KEY: supersecret_dev_key
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
      COOKIE_SECURE: "false"
      COOKIE_SAMESITE: lax
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    image: node:20-alpine
    container_name: financas_frontend
    working_dir: /app
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:
