-- Bancos / instituicoes financeiras registradas no BCB (codigo COMPE).
-- Fonte: STR/SPB - lista publica do Banco Central do Brasil.
-- Idempotencia: run_seeds.py so executa este arquivo se `bancos` estiver vazia.

INSERT INTO bancos (COD, LongName, ShortName, ativo) VALUES
('001', 'Banco do Brasil S.A.', 'Banco do Brasil', 1),
('003', 'Banco da Amazonia S.A.', 'Basa', 1),
('004', 'Banco do Nordeste do Brasil S.A.', 'BNB', 1),
('007', 'Banco Nacional de Desenvolvimento Economico e Social', 'BNDES', 1),
('010', 'Credicoamo Credito Rural Cooperativa', 'Credicoamo', 1),
('011', 'Credit Suisse Hedging-Griffo CV S.A.', 'Credit Suisse', 1),
('012', 'Banco Inbursa S.A.', 'Inbursa', 1),
('014', 'State Street Brasil S.A. - Banco Comercial', 'State Street', 1),
('015', 'UBS Brasil CCTVM S.A.', 'UBS Brasil', 1),
('016', 'Coop. de Credito Mutuo dos Despachantes de Transito de SC e RS', 'Coopcredi', 1),
('017', 'BNY Mellon Banco S.A.', 'BNY Mellon', 1),
('018', 'Banco Tricury S.A.', 'Tricury', 1),
('021', 'Banestes S.A. Banco do Estado do Espirito Santo', 'Banestes', 1),
('024', 'Banco Bandepe S.A.', 'Bandepe', 1),
('025', 'Banco Alfa S.A.', 'Banco Alfa', 1),
('029', 'Banco Itau Consignado S.A.', 'Itau Consignado', 1),
('033', 'Banco Santander (Brasil) S.A.', 'Santander', 1),
('036', 'Banco Bradesco BBI S.A.', 'Bradesco BBI', 1),
('037', 'Banco do Estado do Para S.A.', 'Banpara', 1),
('040', 'Banco Cargill S.A.', 'Cargill', 1),
('041', 'Banco do Estado do Rio Grande do Sul S.A.', 'Banrisul', 1),
('047', 'Banco do Estado de Sergipe S.A.', 'Banese', 1),
('060', 'Confidence CC S.A.', 'Confidence', 1),
('062', 'Hipercard Banco Multiplo S.A.', 'Hipercard', 1),
('063', 'Banco Bradescard S.A.', 'Bradescard', 1),
('064', 'Goldman Sachs do Brasil Banco Multiplo S.A.', 'Goldman Sachs', 1),
('065', 'Banco Andbank (Brasil) S.A.', 'Andbank', 1),
('066', 'Banco Morgan Stanley S.A.', 'Morgan Stanley', 1),
('069', 'Banco Crefisa S.A.', 'Crefisa', 1),
('070', 'BRB - Banco de Brasilia S.A.', 'BRB', 1),
('074', 'Banco J. Safra S.A.', 'J. Safra', 1),
('075', 'Banco ABN Amro S.A.', 'ABN Amro', 1),
('076', 'Banco KDB do Brasil S.A.', 'KDB', 1),
('077', 'Banco Inter S.A.', 'Inter', 1),
('078', 'Haitong Banco de Investimento do Brasil S.A.', 'Haitong', 1),
('079', 'Banco Original do Agronegocio S.A.', 'Original Agro', 1),
('080', 'B&T CC Ltda.', 'B&T', 1),
('081', 'BancoSeguro S.A.', 'BancoSeguro', 1),
('082', 'Banco Topazio S.A.', 'Topazio', 1),
('083', 'Banco da China Brasil S.A.', 'Banco da China', 1),
('084', 'Sistema de Cooperativas Financeiras do Brasil S.A.', 'Uniprime', 1),
('085', 'Coop Central Ailos', 'Ailos', 1),
('088', 'Banco Randon S.A.', 'Randon', 1),
('089', 'CCR Reg Mogiana', 'Credisan', 1),
('091', 'Central de Cooperativas de Economia e Credito Mutuo do Estado do RS', 'Unicred RS', 1),
('092', 'BRK S.A. CFI', 'BRK', 1),
('093', 'Polocred SCMEPP Ltda.', 'Polocred', 1),
('094', 'Banco Finaxis S.A.', 'Finaxis', 1),
('095', 'Travelex Banco de Cambio S.A.', 'Travelex', 1),
('096', 'Banco B3 S.A.', 'B3', 1),
('097', 'Credisis - Central de Cooperativas de Credito Ltda.', 'Credisis', 1),
('098', 'Credialianca CCR', 'Credialianca', 1),
('099', 'Uniprime Central CCC Ltda.', 'Uniprime Central', 1),
('100', 'Planner Corretora de Valores S.A.', 'Planner', 1),
('101', 'Renascenca DTVM Ltda.', 'Renascenca', 1),
('102', 'XP Investimentos CCTVM S.A.', 'XP Investimentos', 1),
('104', 'Caixa Economica Federal', 'Caixa', 1),
('105', 'Lecca CFI S.A.', 'Lecca', 1),
('107', 'Banco BOCOM BBM S.A.', 'BOCOM BBM', 1),
('108', 'PortoCred S.A. CFI', 'PortoCred', 1),
('111', 'Oliveira Trust DTVM S.A.', 'Oliveira Trust', 1),
('113', 'Magliano S.A. CCVM', 'Magliano', 1),
('114', 'Central Cooperativa de Credito no Estado do Espirito Santo', 'Cecoop ES', 1),
('117', 'Advanced CC Ltda.', 'Advanced', 1),
('118', 'Standard Chartered Bank (Brasil) S.A. BI', 'Standard Chartered', 1),
('119', 'Banco Western Union do Brasil S.A.', 'Western Union', 1),
('120', 'Banco Rodobens S.A.', 'Rodobens', 1),
('121', 'Banco Agibank S.A.', 'Agibank', 1),
('122', 'Banco Bradesco BERJ S.A.', 'Bradesco BERJ', 1),
('124', 'Banco Woori Bank do Brasil S.A.', 'Woori Bank', 1),
('125', 'Banco Genial S.A.', 'Genial', 1),
('126', 'BR Partners Banco de Investimento S.A.', 'BR Partners', 1),
('127', 'Codepe CVC S.A.', 'Codepe', 1),
('128', 'MS Bank S.A. Banco de Cambio', 'MS Bank', 1),
('129', 'UBS Brasil Banco de Investimento S.A.', 'UBS BI', 1),
('130', 'Caruana SCFI', 'Caruana', 1),
('131', 'Tullett Prebon Brasil CVC Ltda.', 'Tullett Prebon', 1),
('132', 'ICBC do Brasil Banco Multiplo S.A.', 'ICBC', 1),
('133', 'Confederacao Nacional das Cooperativas Centrais Unicred Ltda.', 'Cresol', 1),
('134', 'BGC Liquidez DTVM Ltda.', 'BGC', 1),
('136', 'Confederacao Nacional das Cooperativas Centrais Unicred', 'Unicred', 1),
('138', 'Get Money CC Ltda.', 'Get Money', 1),
('139', 'Intesa Sanpaolo Brasil S.A. Banco Multiplo', 'Intesa Sanpaolo', 1),
('140', 'Easynvest - Titulo CV S.A.', 'Easynvest', 1),
('142', 'Broker Brasil CC Ltda.', 'Broker Brasil', 1),
('143', 'Treviso CC S.A.', 'Treviso', 1),
('144', 'BEXS Banco de Cambio S.A.', 'BEXS', 1),
('145', 'Levycam CCV Ltda.', 'Levycam', 1),
('146', 'Guitta CC Ltda.', 'Guitta', 1),
('149', 'Facta Financeira S.A. CFI', 'Facta', 1),
('157', 'ICAP do Brasil CTVM Ltda.', 'ICAP', 1),
('159', 'Casa Credito S.A. SCM', 'Casa Credito', 1),
('163', 'Commerzbank Brasil S.A. - Banco Multiplo', 'Commerzbank', 1),
('169', 'Banco Olé Bonsucesso Consignado S.A.', 'Olé Consignado', 1),
('172', 'Albatross CCV S.A.', 'Albatross', 1),
('173', 'BRL Trust DTVM S.A.', 'BRL Trust', 1),
('174', 'Pernambucanas Financiadora S.A. CFI', 'Pernambucanas', 1),
('177', 'Guide Investimentos S.A. CV', 'Guide', 1),
('180', 'CM Capital Markets CCTVM Ltda.', 'CM Capital', 1),
('183', 'Socred S.A. SCMEPP', 'Socred', 1),
('184', 'Banco Itau BBA S.A.', 'Itau BBA', 1),
('188', 'Ativa Investimentos S.A. CTCV', 'Ativa', 1),
('189', 'HS Financeira S.A. CFI', 'HS Financeira', 1),
('190', 'Servicoop - Cooperativa de Credito dos Servidores Publicos', 'Servicoop', 1),
('191', 'Nova Futura CTVM Ltda.', 'Nova Futura', 1),
('194', 'Parmetal DTVM Ltda.', 'Parmetal', 1),
('195', 'Valor SCD S.A.', 'Valor SCD', 1),
('196', 'Fair CC S.A.', 'Fair', 1),
('197', 'Stone Pagamentos S.A.', 'Stone', 1),
('208', 'Banco BTG Pactual S.A.', 'BTG Pactual', 1),
('212', 'Banco Original S.A.', 'Original', 1),
('213', 'Banco Arbi S.A.', 'Arbi', 1),
('217', 'Banco John Deere S.A.', 'John Deere', 1),
('218', 'Banco BS2 S.A.', 'BS2', 1),
('222', 'Banco Credit Agricole Brasil S.A.', 'Credit Agricole', 1),
('224', 'Banco Fibra S.A.', 'Fibra', 1),
('233', 'Banco Cifra S.A.', 'Cifra', 1),
('237', 'Banco Bradesco S.A.', 'Bradesco', 1),
('241', 'Banco Classico S.A.', 'Classico', 1),
('243', 'Banco Master S.A.', 'Master', 1),
('246', 'Banco ABC Brasil S.A.', 'ABC Brasil', 1),
('249', 'Banco Investcred Unibanco S.A.', 'Investcred', 1),
('250', 'BCV - Banco de Credito e Varejo S.A.', 'BCV', 1),
('253', 'Bexs Corretora de Cambio S.A.', 'Bexs CC', 1),
('254', 'Parana Banco S.A.', 'Parana Banco', 1),
('259', 'Moneycorp Banco de Cambio S.A.', 'Moneycorp', 1),
('260', 'Nu Pagamentos S.A. (Nubank)', 'Nubank', 1),
('265', 'Banco Fator S.A.', 'Fator', 1),
('266', 'Banco Cedula S.A.', 'Cedula', 1),
('268', 'Barigui CHSCM S.A.', 'Barigui', 1),
('269', 'HSBC Brasil S.A. Banco de Investimento', 'HSBC BI', 1),
('270', 'Sagitur CC Ltda.', 'Sagitur', 1),
('271', 'IB CCTVM S.A.', 'IB', 1),
('272', 'AGK CC S.A.', 'AGK', 1),
('273', 'CCR de Sao Miguel do Oeste', 'CCR SMO', 1),
('274', 'Money Plus SCMEPP Ltda.', 'Money Plus', 1),
('276', 'Senff S.A. CFI', 'Senff', 1),
('278', 'Genial Investimentos CVM S.A.', 'Genial Inv', 1),
('279', 'CCR de Primavera do Leste', 'CCR Primavera', 1),
('280', 'Avista S.A. CFI', 'Avista', 1),
('281', 'Cooperativa de Credito Rural Coopavel', 'Coopavel', 1),
('283', 'RB Capital Investimentos DTVM Ltda.', 'RB Capital', 1),
('285', 'Frente CC Ltda.', 'Frente', 1),
('286', 'Cooperativa de Credito Rural de Ouro - Sulcredi/Ouro', 'Sulcredi Ouro', 1),
('288', 'Carol DTVM Ltda.', 'Carol', 1),
('289', 'EFX CC Ltda.', 'EFX', 1),
('290', 'PagSeguro Internet S.A.', 'PagSeguro', 1),
('292', 'BS2 DTVM S.A.', 'BS2 DTVM', 1),
('293', 'Lastro RDV DTVM Ltda.', 'Lastro RDV', 1),
('296', 'Vision S.A. CC', 'Vision', 1),
('298', 'Vips CC Ltda.', 'Vips', 1),
('299', 'Banco Sorocred S.A.', 'Sorocred', 1),
('300', 'Banco de la Nacion Argentina', 'BNA', 1),
('301', 'BPP Instituicao de Pagamento S.A.', 'BPP', 1),
('305', 'Aafac SCFI', 'Aafac', 1),
('306', 'Portopar DTVM Ltda.', 'Portopar', 1),
('307', 'Terra Investimentos DTVM Ltda.', 'Terra', 1),
('309', 'Cambionet CC Ltda.', 'Cambionet', 1),
('310', 'VortX DTVM Ltda.', 'VortX', 1),
('311', 'Dourada CC Ltda.', 'Dourada', 1),
('312', 'HSCM SCMEPP Ltda.', 'HSCM', 1),
('313', 'Amazonia CCVM S.A.', 'Amazonia CC', 1),
('315', 'Pi Distribuidora de Titulos e Valores Mobiliarios S.A.', 'Pi', 1),
('318', 'Banco BMG S.A.', 'BMG', 1),
('319', 'OM DTVM Ltda.', 'OM', 1),
('320', 'China Construction Bank (Brasil) BM S.A.', 'CCB Brasil', 1),
('321', 'Crefaz SCMEPP S.A.', 'Crefaz', 1),
('322', 'CCR de Abelardo Luz', 'CCR Abelardo Luz', 1),
('323', 'Mercado Pago - Conta do Mercado Livre', 'Mercado Pago', 1),
('325', 'Orla DTVM S.A.', 'Orla', 1),
('329', 'QI SCD S.A.', 'QI SCD', 1),
('330', 'Banco Bari de Investimentos e Financiamentos S.A.', 'Bari', 1),
('331', 'Fram Capital DTVM S.A.', 'Fram', 1),
('332', 'Acesso Solucoes de Pagamento S.A.', 'Acesso', 1),
('335', 'Banco Digio S.A.', 'Digio', 1),
('336', 'Banco C6 S.A.', 'C6 Bank', 1),
('340', 'Super Pagamentos e Administracao de Meios Eletronicos S.A.', 'Superdigital', 1),
('341', 'Itau Unibanco S.A.', 'Itau', 1),
('342', 'Creditas SCD S.A.', 'Creditas', 1),
('343', 'FFA SCMEPP Ltda.', 'FFA', 1),
('348', 'Banco XP S.A.', 'XP', 1),
('349', 'Al5 S.A. CFI', 'Al5', 1),
('350', 'Cooperativa de Credito Rural de Pequenos Agricultores', 'Crehnor', 1),
('352', 'Toro CTVM Ltda.', 'Toro', 1),
('354', 'Necton Investimentos S.A. CVM', 'Necton', 1),
('355', 'Ótimo SCD S.A.', 'Otimo SCD', 1),
('358', 'Midway S.A. - Credito, Financiamento e Investimento', 'Midway', 1),
('359', 'Zema CFI S.A.', 'Zema', 1),
('360', 'Trinus Capital DTVM S.A.', 'Trinus', 1),
('362', 'Cielo S.A.', 'Cielo', 1),
('363', 'Socopa SC Paulista S.A.', 'Socopa', 1),
('364', 'Gerencianet S.A.', 'Gerencianet', 1),
('365', 'Solidus S.A. CCVM', 'Solidus', 1),
('366', 'Banco Societe Generale Brasil S.A.', 'Societe Generale', 1),
('367', 'Vitreo DTVM S.A.', 'Vitreo', 1),
('368', 'Banco CSF S.A.', 'CSF (Carrefour)', 1),
('370', 'Banco Mizuho do Brasil S.A.', 'Mizuho', 1),
('371', 'Warren CVMC Ltda.', 'Warren', 1),
('373', 'Up.p SEP S.A.', 'Up.p', 1),
('374', 'Realize CFI S.A.', 'Realize', 1),
('376', 'Banco J. P. Morgan S.A.', 'JP Morgan', 1),
('377', 'BMS SCD S.A.', 'BMS', 1),
('378', 'BBC Leasing S.A. - Arrendamento Mercantil', 'BBC Leasing', 1),
('379', 'Cooperforte - Coop Mutuo dos Funcionarios de Instituicoes Financeiras', 'Cooperforte', 1),
('380', 'PicPay Servicos S.A.', 'PicPay', 1),
('381', 'Banco Mercedes-Benz do Brasil S.A.', 'Mercedes-Benz', 1),
('382', 'Fiducia SCMEPP Ltda.', 'Fiducia', 1),
('383', 'Juno - Boletobancario.com Tecnologia de Pagamentos Ltda.', 'Juno', 1),
('384', 'Global Finanças SCMEPP Ltda.', 'Global', 1),
('385', 'Cecm dos Trab. Portuarios da Grande Vitoria', 'Cecm Vitoria', 1),
('386', 'Nu Financeira S.A. SCFI', 'Nu Financeira', 1),
('387', 'Banco Toyota do Brasil S.A.', 'Toyota', 1),
('388', 'Cooperativa de Credito de Livre Admissao - Sicoob Engecred', 'Sicoob Engecred', 1),
('389', 'Banco Mercantil do Brasil S.A.', 'Mercantil', 1),
('390', 'Banco GM S.A.', 'GM', 1),
('391', 'CCR de Ibiam', 'CCR Ibiam', 1),
('393', 'Banco Volkswagen S.A.', 'Volkswagen', 1),
('394', 'Banco Bradesco Financiamentos S.A.', 'Bradesco Fin', 1),
('395', 'F.D''Gold - DTVM Ltda.', 'F.D Gold', 1),
('396', 'Hub Pagamentos S.A.', 'Hub', 1),
('397', 'Listo SCD S.A.', 'Listo', 1),
('398', 'Iderco DTVM Ltda.', 'Iderco', 1),
('399', 'Kirton Bank S.A. - Banco Multiplo', 'Kirton (ex-HSBC)', 1),
('400', 'Cooperativa de Credito, Poupanca e Servicos Financeiros Unicred Vale', 'Unicred Vale', 1),
('401', 'Iugu Servicos na Internet S.A.', 'Iugu', 1),
('402', 'Cobuccio SCD S.A.', 'Cobuccio', 1),
('403', 'Cora SCD S.A.', 'Cora', 1),
('404', 'Sumup SCD S.A.', 'Sumup', 1),
('406', 'Accredito SCD S.A.', 'Accredito', 1),
('407', 'Indio Bank S.A.', 'Indio Bank', 1),
('408', 'Bonuspago SCD S.A.', 'Bonuspago', 1),
('410', 'Planner SCM S.A.', 'Planner SCM', 1),
('411', 'Via Certa Financiadora S.A. - CFI', 'Via Certa', 1),
('412', 'Banco Capital S.A.', 'Capital', 1),
('413', 'Banco BV S.A.', 'BV', 1),
('414', 'Work SCD S.A.', 'Work', 1),
('416', 'Lamara SCD S.A.', 'Lamara', 1),
('418', 'ZIPDIN SCD S.A.', 'Zipdin', 1),
('419', 'NumBrs SCD S.A.', 'NumBrs', 1),
('421', 'Lar SCD S.A.', 'Lar', 1),
('422', 'Banco Safra S.A.', 'Safra', 1),
('423', 'Coluna CCV S.A.', 'Coluna', 1),
('425', 'Socinal S.A. - CFI', 'Socinal', 1),
('426', 'Biorc Financeira - CFI S.A.', 'Biorc', 1),
('427', 'CCEM dos Servidores Publicos Estaduais do RS - Cooperifes', 'Cooperifes', 1),
('428', 'Cred-System SCD S.A.', 'Cred-System', 1),
('429', 'Crediare S.A. - CFI', 'Crediare', 1),
('430', 'Cooperativa de Credito Rural Seara - Crediseara', 'Crediseara', 1),
('433', 'BR Advisory Partners SCM S.A.', 'BR Advisory', 1),
('435', 'Delcred SCD S.A.', 'Delcred', 1),
('438', 'Planner Trustee DTVM Ltda.', 'Planner Trustee', 1),
('439', 'Id Corretora de Titulos e Valores Mobiliarios S.A.', 'Id CTVM', 1),
('440', 'Credibrf - Cooperativa de Credito', 'Credibrf', 1),
('442', 'Magnetis - DTVM Ltda.', 'Magnetis', 1),
('443', 'Credihome SCD', 'Credihome', 1),
('444', 'Trustee DTVM Ltda.', 'Trustee', 1),
('445', 'Plantae S.A. - CFI', 'Plantae', 1),
('447', 'Mirae Asset Wealth Management (Brazil) CCTVM Ltda.', 'Mirae Asset', 1),
('448', 'Hemera DTVM Ltda.', 'Hemera', 1),
('449', 'DM SA CFI', 'DM', 1),
('450', 'Fitbank Pagamentos Eletronicos S.A.', 'Fitbank', 1),
('451', 'Hr Digital SCD S.A.', 'Hr Digital', 1),
('452', 'Credifit SCD S.A.', 'Credifit', 1),
('454', 'Mérito DTVM Ltda.', 'Merito', 1),
('456', 'Banco MUFG Brasil S.A.', 'MUFG', 1),
('457', 'UY3 SCD S.A.', 'UY3', 1),
('458', 'Hedge Investments DTVM Ltda.', 'Hedge', 1),
('459', 'CCM dos Servidores Publicos do Estado de SP - Credisan', 'Credisan SP', 1),
('460', 'Asaas Gestao Financeira IP S.A.', 'Asaas', 1),
('461', 'Asaas IP S.A.', 'Asaas IP', 1),
('462', 'Stark SCD S.A.', 'Stark', 1),
('463', 'Azumi DTVM', 'Azumi', 1),
('464', 'Banco Sumitomo Mitsui Brasileiro S.A.', 'Sumitomo Mitsui', 1),
('465', 'Capital Consig SCD S.A.', 'Capital Consig', 1),
('467', 'Master S.A. CCTVM', 'Master CCTVM', 1),
('468', 'PortoSeg S.A. - CFI', 'PortoSeg', 1),
('469', 'Ligga SCD S.A.', 'Ligga', 1),
('470', 'CDC SCD S.A.', 'CDC', 1),
('471', 'Cecm dos Servidores Pub Est Esp Santo', 'Cecm ES', 1),
('473', 'Banco Caixa Geral - Brasil S.A.', 'Caixa Geral', 1),
('475', 'Banco Yamaha Motor do Brasil S.A.', 'Yamaha', 1),
('477', 'Citibank N.A.', 'Citibank', 1),
('478', 'Gazincred S.A. SCFI', 'Gazincred', 1),
('479', 'Banco ItauBank S.A.', 'ItauBank', 1),
('481', 'Superlogica SCD S.A.', 'Superlogica', 1),
('482', 'Sbcash SCD', 'Sbcash', 1),
('487', 'Deutsche Bank S.A. - Banco Alemao', 'Deutsche Bank', 1),
('488', 'JPMorgan Chase Bank, National Association', 'JPMorgan Chase', 1),
('492', 'ING Bank N.V.', 'ING', 1),
('495', 'Banco de la Provincia de Buenos Aires', 'BAPRO', 1),
('505', 'Banco Credit Suisse (Brasil) S.A.', 'Credit Suisse BR', 1),
('545', 'Senso CCVM S.A.', 'Senso', 1),
('600', 'Banco Luso Brasileiro S.A.', 'Luso Brasileiro', 1),
('604', 'Banco Industrial do Brasil S.A.', 'Industrial', 1),
('610', 'Banco VR S.A.', 'VR', 1),
('611', 'Banco Paulista S.A.', 'Paulista', 1),
('612', 'Banco Guanabara S.A.', 'Guanabara', 1),
('613', 'Omni Banco S.A.', 'Omni', 1),
('623', 'Banco Pan S.A.', 'Pan', 1),
('626', 'Banco C6 Consignado S.A.', 'C6 Consignado', 1),
('630', 'Banco Smartbank S.A.', 'Smartbank', 1),
('633', 'Banco Rendimento S.A.', 'Rendimento', 1),
('634', 'Banco Triangulo S.A.', 'Tribanco', 1),
('637', 'Banco Sofisa S.A.', 'Sofisa', 1),
('643', 'Banco Pine S.A.', 'Pine', 1),
('652', 'Itau Unibanco Holding S.A.', 'Itau Holding', 1),
('653', 'Banco Voiter S.A.', 'Voiter (ex-Indusval)', 1),
('654', 'Banco Digimais S.A.', 'Digimais', 1),
('655', 'Banco Votorantim S.A.', 'Votorantim', 1),
('707', 'Banco Daycoval S.A.', 'Daycoval', 1),
('712', 'Banco Ourinvest S.A.', 'Ourinvest', 1),
('739', 'Banco Cetelem S.A.', 'Cetelem', 1),
('741', 'Banco Ribeirao Preto S.A.', 'Ribeirao Preto', 1),
('743', 'Banco Semear S.A.', 'Semear', 1),
('745', 'Banco Citibank S.A.', 'Citibank S.A.', 1),
('746', 'Banco Modal S.A.', 'Modal', 1),
('747', 'Banco Rabobank International Brasil S.A.', 'Rabobank', 1),
('748', 'Banco Cooperativo Sicredi S.A.', 'Sicredi', 1),
('751', 'Scotiabank Brasil S.A. Banco Multiplo', 'Scotiabank', 1),
('752', 'Banco BNP Paribas Brasil S.A.', 'BNP Paribas', 1),
('753', 'Novo Banco Continental S.A. - Banco Multiplo', 'Novo Banco Continental', 1),
('754', 'Banco Sistema S.A.', 'Sistema', 1),
('755', 'Bank of America Merrill Lynch Banco Multiplo S.A.', 'Bank of America', 1),
('756', 'Banco Cooperativo do Brasil S.A. - Bancoob', 'Sicoob', 1),
('757', 'Banco KEB Hana do Brasil S.A.', 'KEB Hana', 1);
